### ISSUE TITLE
SOME IDEAS for Random Loot chest

### ISSUE THREAD

**Issue by KazMNF** [MrABCDevelopment/RandomLootChest#11]
Hello. Thanks for making such good plugin.
I have some ideas for random loot chest.
1. Drag to drop making Chests for fast and easy making chests.
2. More plugin compabilities. like InfiniteVouchers, Oraxen
3. After a looting chest will disappear and reappear after cooldown ends.

**Comment by MrABCDevelopment** [comment]
Hey, currently, I'm working on few projects, but I like some of your ideas and I'll do the best to bring them into the RandomLootChest.

**Comment by MrABCDevelopment** [comment]
In the latest RandomLootChest release, there is feature disappearing and reappearing chest, also added support for MythicMobs items. I'll keep that in mind to add more hooks to other plugins. Thank you for your suggestions.
