### ISSUE TITLE
RLC messing with region cache keeping chunks loaded and causing TPS dips

### ISSUE THREAD

**Issue by mercurialmusic** [MrABCDevelopment/RandomLootChest#18]
After discussion with Paper staff we were able to determine that RandomLootChest was causing the following error: https://gist.github.com/mercurialmusic/e5742d26028ebe513928cd0dfa456121

According to them, RLC is "screwing with the servers region file cache". This is causing chunks where chests exist to load quite randomly without anyone in the world, often many dozens of chunks at a time, causing unnecessary resource drain and TPS dips on the server.

Occasionally, reloading the chests or running a location fix can help mitigate the chunk loading temporarily, but it often starts back up again.

Not sure if it's related, but doing a location fix also spams the following error:
https://gist.github.com/mercurialmusic/e5742d26028ebe513928cd0dfa456121

Currently running RandomLootChest-v1.8.2.2 with git-Paper-378 (MC: 1.20.4)

Thanks!

**Comment by MrABCDevelopment** [comment]
Hey, this should be fixed using newest version (v1.8.3.0), if there will be any problem - please write it down here.

**Comment by mercurialmusic** [comment]
> Hey, this should be fixed using newest version (v1.8.3.0), if there will be any problem - please write it down here.

Thanks for the quick response! However, the update doesn't seem to have changed any behavior with the chunk loading at least, although I no longer get the ClosedChannelException error.

**Comment by mercurialmusic** [comment]
> Hey, this should be fixed using newest version (v1.8.3.0), if there will be any problem - please write it down here.

Thanks for the quick response! However, the update doesn't seem to have changed any behavior with the chunk loading at least, although I no longer get the ClosedChannelException error.

**Comment by MrABCDevelopment** [comment]
Should be fixed after few patches.
